In [3]:
def myjucheng(A, B):
    # 获取矩阵维度
    m = len(A)
    n = len(A[0]) 
    p = len(B[0]) 
    C = [[0 for _ in range(p)] for _ in range(m)] 
    # 三重循环计算矩阵乘法
    for i in range(m):
        for j in range(p):
            for k in range(n):
                C[i][j] += A[i][k] * B[k][j]
    
    return C


In [9]:
A = [[1, 2], [4, 5]]
B = [[7, 8], [9, 10]]

print("矩阵A:")
for row in A:
    print(row)
    
print("矩阵B:")#换行
for row in B:
    print(row)
    
C = myjucheng(A, B)
print("矩阵乘法结果C:")
for row in C:
    print(row)


矩阵A:
[1, 2]
[4, 5]
矩阵B:
[7, 8]
[9, 10]
矩阵乘法结果C:
[25, 28]
[73, 82]


In [6]:
import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])
print("矩阵A:")
print(A)
print("矩阵B:")
print(B)
C = np.dot(A, B)
print("矩阵乘法结果C:")
print(C)

矩阵A:
[[1 2 3]
 [4 5 6]]
矩阵B:
[[ 7  8]
 [ 9 10]
 [11 12]]
矩阵乘法结果C:
[[ 58  64]
 [139 154]]


In [18]:
import numpy as np
np.random.seed(42)
n = 3
A = np.random.randint(1, 10, size=(n, 2, 3))#n个2*3
B = np.random.randint(1, 10, size=(3, 2))

print("批量矩阵A (shape={}):".format(A.shape))
print(A)
print("矩阵B (shape={}):".format(B.shape))
print(B)
C = np.matmul(A, B)
print("批量矩阵乘法结果C (shape={}):".format(C.shape))
print(C)

批量矩阵A (shape=(3, 2, 3)):
[[[7 4 8]
  [5 7 3]]

 [[7 8 5]
  [4 8 8]]

 [[3 6 5]
  [2 8 6]]]
矩阵B (shape=(3, 2)):
[[2 5]
 [1 6]
 [9 1]]
批量矩阵乘法结果C (shape=(3, 2, 2)):
[[[90 67]
  [44 70]]

 [[67 88]
  [88 76]]

 [[57 56]
  [66 64]]]
