In [8]:
import numpy as np
X = np.array([[1, 1],
              [1, 2], 
              [1, 3]])
y = np.array([[2],
              [3.1],
              [4]])
β = np.linalg.inv(X.T @ X) @ X.T @ y
print("模型系数:")
print(β)

模型系数:
[[1.03333333]
 [1.        ]]


In [11]:
import numpy as np
X = np.array([[1, 1], [1, 2], [1, 3]])
y = np.array([2, 3.1, 4])
X = np.column_stack([np.ones_like(x_data), x_data])
print("设计矩阵X:")
print(X)
XTX = X.T @ X
print("X^T*X矩阵:")
print(XTX)
XTy = X.T @ y_data
print("X^T*y向量:")
print(XTy)
beta = XTX_inv @ XTy
print("回归系数β:")
print(beta)

设计矩阵X:
[[1 1]
 [1 2]
 [1 3]]
X^T*X矩阵:
[[ 3  6]
 [ 6 14]]
X^T*y向量:
[ 9.1 20.2]
回归系数β:
[1.03333333 1.        ]
