In [7]:
import numpy as np
a = [0, 1, 2, 3, 4, 5]
print(a)
a = np.array(a)
a = a.reshape(3, 2)
print(a)

[0, 1, 2, 3, 4, 5]
[[0 1]
 [2 3]
 [4 5]]


In [13]:
np.zeros(3)
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
a = np.arange(10)**3
print(a)
print(a[2])
print(a[2:5])

[  0   1   8  27  64 125 216 343 512 729]
8
[ 8 27 64]


In [18]:
a = np.arange(15).reshape(3, 5)
print(a)
print(a[:2, :4])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0 1 2 3]
 [5 6 7 8]]


In [19]:
import numpy as np

A = np.array([[1, 1], [0, 1]])  
B = np.array([[2, 0], [3, 4]])  
print(A * B)
print(A @ B)
print(np.dot(A, B))

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


In [20]:
import numpy as np
a = np.arange(15).reshape(3, 5)
print(a)
a.reshape(5, 3)
a.reshape(15, 1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14]])